### ISSUE TITLE
Wildcard SAN input field is shown twice.

### ISSUE THREAD

**Issue by MnM202** [gogetssl/whmcs-addon#209]
**Describe the bug**
The wildcard san input field is shown twice when trying to configure a mult-domain flex SSL certificate.

**To Reproduce**
1. Create a GoGetSSL@ Multi-Domain SSL certificate
2. Generate pricing for SAN.
3. Generate pricing for wildcard SANs.
4. Fill in pricing for both
5. Order the product in WHMCS
6. Add a few additional SANs of both Single and Wildcard type.
7. Notice a double input field for wildcard SANs in the interface. Only the bottom one works.

**Expected behavior**
I expect to see only one input field for wildcard sans in flex certificates that have both SANs and Wildcard SANs.

**Screenshots**
![GoGetSSL Mult-Domain SSL](https://user-images.githubusercontent.com/113260396/189497818-b732c7e8-7d9f-49e7-93e4-ed3790149060.png)
![SAN Pricing](https://user-images.githubusercontent.com/113260396/189497824-afbefcba-7d8a-4c3f-a360-0ac1bf843642.png)
![WildSAN Pricing](https://user-images.githubusercontent.com/113260396/189497825-fbd3d51d-c3e0-48e4-82a0-99338805f937.png)

Here you can see the wildcard sans having two input fields. Only the bottom one works.
![Wildcard SANs displayed twice](https://user-images.githubusercontent.com/113260396/189497716-a0d9f4af-00cc-4771-b024-e4460a69b4ee.png)

**Comment by vlad-evg** [comment]
Developers are checking it now

**Comment by MnM202** [comment]
Hi Vlad,

Thank you for coming back to me. Much appreciated.

The new version looks much improved.
- I no longer see the wildcard input form twice.
- I am able to register both domains and wildcards.

While testing, i did notice two additional issues that seem to be in 2.7.5 as well.
I don't think they are related to your current code changes.

- Additional Wildcard SANs cannot be added with a reissue after the certificate is ordered.
  Even when the original order still has empty spots.
  If i look in the GoGetSSL admin interface i also see only one wildcard SAN on the certificate.
- If you perform two reissues on the same certificate the domain SANs appear comma separated in the domain field. ( both SANs and wildcard SANs merged together. ). Also some SANs are no longer there.

Do you wish for me to raise these as separate issues? Or shall we proceed testing from here.

![CountOfWildcardSANsExceeded](https://user-images.githubusercontent.com/113260396/189684548-ef8c1a7a-e3fc-4ed1-b310-92203555c421.png)
![OnlyOneWildcardSan](https://user-images.githubusercontent.com/113260396/189684551-fc4efa37-b8c5-483e-9621-619d1ab8f3b1.png)
![SANandWildcardMergedTogether](https://user-images.githubusercontent.com/113260396/189684554-1fdc129c-d179-42d4-be0b-313fc02c983f.png)

**Comment by vlad-evg** [comment]
Developers are checking that too. Thank you for the help

**Comment by MnM202** [comment]
Small update. Version 2.7.6 has now been released.
- I can now re-issue the SSL certificate one time and add another wildcard SAN to it and the resulting certificate works.
- The amount of regular sans does appear to be stable now on reissue in the gogetssl web interface.

I still experience the following issues:
- The wildcard sans in the certificate in the gogetssl portal keep increasing with each reissue.
- On the second reissue the domains show up in the interface as a comma separated list in the SAN input box.
![Screenshot 2022-09-17 at 00 05 46](https://user-images.githubusercontent.com/113260396/190812402-1cfc9667-eb95-4aa6-803e-1df8867c5029.png)

**Comment by vlad-evg** [comment]
Please try 2.7.6, it should solve the issue
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.7.6

**Comment by MnM202** [comment]
Hi Vlad,

The module is better, but there is still an issue left:
1) Order an SSL certificate ( this will work fine and the SAN count in gogetssl is correct ).
2) Reissue the ssl certificate and modify it.
3) Wait until it gets issued. ( the san count is now no longer correct but the certificate will get issues with the correct SANs )
4) Reissue the ssl certificate again. ( Now the domains will show as a , seperated list in the SAN domains field. )

I made sure to clean the template files as well.
But i still get this issue in the latest 2.7.6 module.

**Comment by vlad-evg** [comment]
Please try 2.7.6a
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.7.6a

**Comment by MnM202** [comment]
Hi Vlad,

It is getting closer. But not completely fixed yet for me.

1) On the first reissue of the certificate i still see the SAN/Wildcard SAN count increase on the gogetssl.com side of things.

2) On the second reissue i now see the following in SANs:
domain1.com,domain2.com
And the following in the wildcard SANs box:
*.domain3.com,*.domain4.com

So the SAN types are split up now. But the individual domains are still , separated.

**Comment by vlad-evg** [comment]
Hope that would do all you need (

https://github.com/gogetssl/whmcs-addon/releases/tag/v2.7.7a

**Comment by vlad-evg** [comment]
Can you please check compare option on GIT?
https://www.screencast.com/t/MkmCGqBPWyk

**Comment by MnM202** [comment]
Hi Vlad,

Things are coming together now. I am able to reissue for an unlimited amount of times now and the domains are always in the correct spot. So this makes the module usable from a user perspective.

During my renewal i did manage to get into a situation where the the gogetssl.com website displays the wildcard san count incorrectly. ( one additional san got added on renewal ) but this did not effect the reissue procedure. But i have not found a clear way to reproduce that one yet.

All in all the module is now in a much better shape for me.

**Comment by vlad-evg** [comment]
Let us know if the problem will be reproduced again!
