### ISSUE TITLE
Server Type Missing Options + Certificate Approval Email Form Broken

### ISSUE THREAD

**Issue by shabsta** [gogetssl/whmcs-addon#60]
**Describe the bug**
When attempting to configure a new Comodo PositiveSSL the Server Type drop down is missing many of the server types, and on the certificate approval email we're unable to proceed with the validation type.
**To Reproduce**
Take a look at the screenshots
 **Server Type drop down**
![2019-08-30_15-10-51](https://user-images.githubusercontent.com/43058981/64024039-d3e3b200-cb39-11e9-831a-b37345217812.png)
**certificate approval email**
![2019-08-30_15-11-59](https://user-images.githubusercontent.com/43058981/64024040-d3e3b200-cb39-11e9-8894-6f11887d3c83.png)

**Comment by vlad-evg** [comment]
Dear Shabsta,

It is not a bug. All SSL certificates are compatible now with all server software. That is why now we just need to know 2 of them.

Empty emails were fixed starting at 2.1.5 version, now 2.1.9 available
https://github.com/gogetssl/whmcs-addon/releases

Let us know if more questions

**Comment by shabsta** [comment]
Re-opening this issue as I've updated to version 2.1.9 and the issue still exists - unable to select validation method - see screenshots below

**Confirmation of module version**
![2019-09-02_11-35-02](https://user-images.githubusercontent.com/43058981/64106857-5a3a0700-cd79-11e9-8e26-9838e695e216.png)

**Screenshot showing issue**
![2019-09-02_11-31-07](https://user-images.githubusercontent.com/43058981/64106859-5ad29d80-cd79-11e9-8298-20fe9c07ca15.png)


I then loaded the latest module onto a test environment and am unable to proceed past the configuration page

**Error when attempting to load configuration page on fresh whmcs install**
Screenshot below
![2019-09-02_12-00-10](https://user-images.githubusercontent.com/43058981/64107068-e51b0180-cd79-11e9-9b95-f6e559cc6271.png)

**Comment by vlad-evg** [comment]
Please provide WHMCS admin and FTP access to let developers check your issue. you can send it in Ticket from Client area

**Comment by vlad-evg** [comment]
Do you still have issues? Can you provide access please?
